/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.galenus.telas;

import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 *
 * @author arthu
 */
public class AlterarCadastro extends javax.swing.JFrame {

    /**
     * Creates new form Rh
     */
    public AlterarCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_Buscar = new javax.swing.JButton();
        Button_Des_Acesso = new javax.swing.JButton();
        Button_Salvar = new javax.swing.JButton();
        Button_Limpar = new javax.swing.JButton();
        Button_Sair = new javax.swing.JButton();
        TextField_CPF_Busca = new javax.swing.JTextField();
        TextField_Endereco = new javax.swing.JTextField();
        TextField_Telefone = new javax.swing.JTextField();
        TextField_CPF = new javax.swing.JTextField();
        TextField_Nome = new javax.swing.JTextField();
        Label_fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1240, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Button_Buscar.setFont(new java.awt.Font("Constantia", 1, 30)); // NOI18N
        Button_Buscar.setText("Buscar");
        Button_Buscar.setFocusPainted(false);
        Button_Buscar.setMargin(new java.awt.Insets(11, 14, 3, 14));
        getContentPane().add(Button_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, 200, 50));

        Button_Des_Acesso.setFont(new java.awt.Font("Constantia", 1, 20)); // NOI18N
        Button_Des_Acesso.setText("Desativar Acesso");
        Button_Des_Acesso.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Button_Des_Acesso.setFocusable(false);
        Button_Des_Acesso.setMargin(new java.awt.Insets(11, 14, 3, 14));
        Button_Des_Acesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Des_AcessoActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Des_Acesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 640, 220, 40));

        Button_Salvar.setFont(new java.awt.Font("Constantia", 1, 20)); // NOI18N
        Button_Salvar.setText("Salvar");
        Button_Salvar.setMargin(new java.awt.Insets(11, 14, 3, 14));
        getContentPane().add(Button_Salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 640, 160, 40));

        Button_Limpar.setFont(new java.awt.Font("Constantia", 1, 20)); // NOI18N
        Button_Limpar.setText("Limpar");
        Button_Limpar.setMargin(new java.awt.Insets(11, 14, 3, 14));
        getContentPane().add(Button_Limpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 640, 160, 40));

        Button_Sair.setFont(new java.awt.Font("Constantia", 1, 20)); // NOI18N
        Button_Sair.setText("Sair");
        Button_Sair.setMargin(new java.awt.Insets(11, 14, 3, 14));
        getContentPane().add(Button_Sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 640, 160, 40));

        TextField_CPF_Busca.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TextField_CPF_Busca.setForeground(new java.awt.Color(153, 153, 153));
        TextField_CPF_Busca.setText("CPF:");
        TextField_CPF_Busca.setMargin(new java.awt.Insets(2, 10, 2, 6));
        TextField_CPF_Busca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextField_CPF_BuscaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextField_CPF_BuscaFocusLost(evt);
            }
        });
        getContentPane().add(TextField_CPF_Busca, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 460, 50));

        TextField_Endereco.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TextField_Endereco.setForeground(new java.awt.Color(153, 153, 153));
        TextField_Endereco.setText("Endereço:");
        TextField_Endereco.setMargin(new java.awt.Insets(2, 10, 2, 6));
        TextField_Endereco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextField_EnderecoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextField_EnderecoFocusLost(evt);
            }
        });
        getContentPane().add(TextField_Endereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, 360, 50));

        TextField_Telefone.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TextField_Telefone.setForeground(new java.awt.Color(153, 153, 153));
        TextField_Telefone.setText("Telefone:");
        TextField_Telefone.setMargin(new java.awt.Insets(2, 10, 2, 6));
        TextField_Telefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextField_TelefoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextField_TelefoneFocusLost(evt);
            }
        });
        getContentPane().add(TextField_Telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 490, 360, 50));

        TextField_CPF.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TextField_CPF.setForeground(new java.awt.Color(153, 153, 153));
        TextField_CPF.setText("CPF:");
        TextField_CPF.setMargin(new java.awt.Insets(2, 10, 2, 6));
        TextField_CPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextField_CPFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextField_CPFFocusLost(evt);
            }
        });
        getContentPane().add(TextField_CPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 360, 50));

        TextField_Nome.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TextField_Nome.setForeground(new java.awt.Color(153, 153, 153));
        TextField_Nome.setText("Nome:");
        TextField_Nome.setMargin(new java.awt.Insets(2, 10, 2, 6));
        TextField_Nome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextField_NomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextField_NomeFocusLost(evt);
            }
        });
        getContentPane().add(TextField_Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 360, 50));

        Label_fundo.setAlignmentY(0.0F);
        Label_fundo.setDoubleBuffered(true);
        Label_fundo.setFocusable(false);
        Label_fundo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Label_fundo.setRequestFocusEnabled(false);
        getContentPane().add(Label_fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Button_Des_AcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Des_AcessoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_Des_AcessoActionPerformed

    private void TextField_NomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextField_NomeFocusGained
        if(TextField_Nome.getText().equals("Nome:")){
            TextField_Nome.setForeground(new Color(0, 0, 0));
            TextField_Nome.setText("");
        }
    }//GEN-LAST:event_TextField_NomeFocusGained

    private void TextField_NomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextField_NomeFocusLost
        if(TextField_Nome.getText().equals("")){
            TextField_Nome.setText("Nome:");
            TextField_Nome.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_TextField_NomeFocusLost

    private void TextField_EnderecoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextField_EnderecoFocusGained
        if(TextField_Endereco.getText().equals("Endereço:")){
            TextField_Endereco.setForeground(new Color(0, 0, 0));
            TextField_Endereco.setText("");
        }
    }//GEN-LAST:event_TextField_EnderecoFocusGained

    private void TextField_CPFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextField_CPFFocusGained
        if(TextField_CPF.getText().equals("CPF:")){
            TextField_CPF.setForeground(new Color(0, 0, 0));
            TextField_CPF.setText("");
        }
    }//GEN-LAST:event_TextField_CPFFocusGained

    private void TextField_TelefoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextField_TelefoneFocusGained
        if(TextField_Telefone.getText().equals("Telefone:")){
            TextField_Telefone.setForeground(new Color(0, 0, 0));
            TextField_Telefone.setText("");
        }
    }//GEN-LAST:event_TextField_TelefoneFocusGained

    private void TextField_CPF_BuscaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextField_CPF_BuscaFocusGained
        if(TextField_CPF_Busca.getText().equals("CPF:")){
            TextField_CPF_Busca.setForeground(new Color(0, 0, 0));
            TextField_CPF_Busca.setText("");
        }
    }//GEN-LAST:event_TextField_CPF_BuscaFocusGained

    private void TextField_CPF_BuscaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextField_CPF_BuscaFocusLost
        if(TextField_CPF_Busca.getText().equals("")){
            TextField_CPF_Busca.setText("CPF:");
            TextField_CPF_Busca.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_TextField_CPF_BuscaFocusLost

    private void TextField_EnderecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextField_EnderecoFocusLost
        if(TextField_Endereco.getText().equals("")){
            TextField_Endereco.setText("Endereço:");
            TextField_Endereco.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_TextField_EnderecoFocusLost

    private void TextField_CPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextField_CPFFocusLost
        if(TextField_CPF.getText().equals("")){
            TextField_CPF.setText("CPF:");
            TextField_CPF.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_TextField_CPFFocusLost

    private void TextField_TelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextField_TelefoneFocusLost
        if(TextField_Telefone.getText().equals("")){
            TextField_Telefone.setText("Telefone:");
            TextField_Telefone.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_TextField_TelefoneFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Buscar;
    private javax.swing.JButton Button_Des_Acesso;
    private javax.swing.JButton Button_Limpar;
    private javax.swing.JButton Button_Sair;
    private javax.swing.JButton Button_Salvar;
    private javax.swing.JLabel Label_fundo;
    private javax.swing.JTextField TextField_CPF;
    private javax.swing.JTextField TextField_CPF_Busca;
    private javax.swing.JTextField TextField_Endereco;
    private javax.swing.JTextField TextField_Nome;
    private javax.swing.JTextField TextField_Telefone;
    // End of variables declaration//GEN-END:variables
    
    private static AlterarCadastro telaUnica;
    
    public static AlterarCadastro getRhAlterarCad(){
        if(telaUnica == null){
            telaUnica = new AlterarCadastro();
        }
        return telaUnica;
    }

}
