/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.galenus.telas;

/**
 *
 * @author arthu
 */
public class AreaRecepcao extends javax.swing.JFrame {

    /**
     * Creates new form RCP_Main
     */
    public AreaRecepcao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_Agendar_Con = new javax.swing.JButton();
        Button_Visualizar_Con = new javax.swing.JButton();
        Button_Confirmar_Con = new javax.swing.JButton();
        Button_Cancelar_Con = new javax.swing.JButton();
        Button_Cad_Paciente = new javax.swing.JButton();
        Button_Sair = new javax.swing.JButton();
        Label_fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Button_Agendar_Con.setFont(new java.awt.Font("Constantia", 1, 30)); // NOI18N
        Button_Agendar_Con.setText("Agendar Consulta");
        Button_Agendar_Con.setMargin(new java.awt.Insets(15, 14, 3, 14));
        Button_Agendar_Con.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Agendar_ConActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Agendar_Con, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 360, 50));

        Button_Visualizar_Con.setFont(new java.awt.Font("Constantia", 1, 30)); // NOI18N
        Button_Visualizar_Con.setText("Visualizar Consulta");
        Button_Visualizar_Con.setMargin(new java.awt.Insets(15, 14, 3, 14));
        Button_Visualizar_Con.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Visualizar_ConActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Visualizar_Con, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 280, 360, 50));

        Button_Confirmar_Con.setFont(new java.awt.Font("Constantia", 1, 30)); // NOI18N
        Button_Confirmar_Con.setText("Confirmar Consulta");
        Button_Confirmar_Con.setMargin(new java.awt.Insets(15, 14, 3, 14));
        Button_Confirmar_Con.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Confirmar_ConActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Confirmar_Con, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 360, 50));

        Button_Cancelar_Con.setFont(new java.awt.Font("Constantia", 1, 30)); // NOI18N
        Button_Cancelar_Con.setText("Cancelar Consulta");
        Button_Cancelar_Con.setMargin(new java.awt.Insets(15, 14, 3, 14));
        getContentPane().add(Button_Cancelar_Con, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, 360, 50));

        Button_Cad_Paciente.setFont(new java.awt.Font("Constantia", 1, 30)); // NOI18N
        Button_Cad_Paciente.setText("Cadastrar Paciente");
        Button_Cad_Paciente.setMargin(new java.awt.Insets(15, 14, 3, 14));
        Button_Cad_Paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Cad_PacienteActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Cad_Paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 480, 360, 50));

        Button_Sair.setFont(new java.awt.Font("Constantia", 1, 20)); // NOI18N
        Button_Sair.setText("Sair");
        Button_Sair.setMargin(new java.awt.Insets(11, 14, 3, 14));
        getContentPane().add(Button_Sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 640, 160, 40));

        Label_fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Recepção.png"))); // NOI18N
        getContentPane().add(Label_fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_Cad_PacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Cad_PacienteActionPerformed
        CadastraPaciente.getRcpCadPaciente().setVisible(true);
    }//GEN-LAST:event_Button_Cad_PacienteActionPerformed

    private void Button_Confirmar_ConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Confirmar_ConActionPerformed
        ConfirmaConsulta.getRcpConfirmarCon().setVisible(true);
    }//GEN-LAST:event_Button_Confirmar_ConActionPerformed

    private void Button_Visualizar_ConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Visualizar_ConActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_Visualizar_ConActionPerformed

    private void Button_Agendar_ConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Agendar_ConActionPerformed
        AgendaConsulta.getRcpAgendarCon().setVisible(true);
    }//GEN-LAST:event_Button_Agendar_ConActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AreaRecepcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AreaRecepcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AreaRecepcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AreaRecepcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AreaRecepcao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Agendar_Con;
    private javax.swing.JButton Button_Cad_Paciente;
    private javax.swing.JButton Button_Cancelar_Con;
    private javax.swing.JButton Button_Confirmar_Con;
    private javax.swing.JButton Button_Sair;
    private javax.swing.JButton Button_Visualizar_Con;
    private javax.swing.JLabel Label_fundo;
    // End of variables declaration//GEN-END:variables

    private static AreaRecepcao telaUnica;
    
    public static AreaRecepcao getRCPMain(){
        if(telaUnica == null){
            telaUnica = new AreaRecepcao();
        }
        return telaUnica;
    }


}
