/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.galenus.telas;

import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

/**
 * @author arthu
 */
@Component
@Slf4j
public class AreaRecepcao extends javax.swing.JFrame {

    /**
     * Creates new form RCP_Main
     */
    public AreaRecepcao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btAgendarConsulta = new javax.swing.JButton();
        btVisualizarConsulta = new javax.swing.JButton();
        btConfirmarConsulta = new javax.swing.JButton();
        btCancelarConsulta = new javax.swing.JButton();
        btCadastrarPaciente = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        Label_fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btAgendarConsulta.setFont(new java.awt.Font("Constantia", 1, 30)); // NOI18N
        btAgendarConsulta.setText("Agendar Consulta");
        btAgendarConsulta.setMargin(new java.awt.Insets(15, 14, 3, 14));
        btAgendarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgendarConsultaActionPerformed(evt);
            }
        });
        getContentPane().add(btAgendarConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 360, 50));

        btVisualizarConsulta.setFont(new java.awt.Font("Constantia", 1, 30)); // NOI18N
        btVisualizarConsulta.setText("Visualizar Consulta");
        btVisualizarConsulta.setMargin(new java.awt.Insets(15, 14, 3, 14));
        btVisualizarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVisualizarConsultaActionPerformed(evt);
            }
        });
        getContentPane().add(btVisualizarConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 280, 360, 50));

        btConfirmarConsulta.setFont(new java.awt.Font("Constantia", 1, 30)); // NOI18N
        btConfirmarConsulta.setText("Confirmar Consulta");
        btConfirmarConsulta.setMargin(new java.awt.Insets(15, 14, 3, 14));
        btConfirmarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmarConsultaActionPerformed(evt);
            }
        });
        getContentPane().add(btConfirmarConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 360, 50));

        btCancelarConsulta.setFont(new java.awt.Font("Constantia", 1, 30)); // NOI18N
        btCancelarConsulta.setText("Cancelar Consulta");
        btCancelarConsulta.setMargin(new java.awt.Insets(15, 14, 3, 14));
        getContentPane().add(btCancelarConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, 360, 50));

        btCadastrarPaciente.setFont(new java.awt.Font("Constantia", 1, 30)); // NOI18N
        btCadastrarPaciente.setText("Cadastrar Paciente");
        btCadastrarPaciente.setMargin(new java.awt.Insets(15, 14, 3, 14));
        btCadastrarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(btCadastrarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 480, 360, 50));

        btSair.setFont(new java.awt.Font("Constantia", 1, 20)); // NOI18N
        btSair.setText("Sair");
        btSair.setMargin(new java.awt.Insets(11, 14, 3, 14));
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        getContentPane().add(btSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 640, 160, 40));

        Label_fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Recepção.png"))); // NOI18N
        getContentPane().add(Label_fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarPacienteActionPerformed
        CadastraPaciente cadastraPaciente = new CadastraPaciente();
        cadastraPaciente.setVisible(true);
    }//GEN-LAST:event_btCadastrarPacienteActionPerformed

    private void btConfirmarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmarConsultaActionPerformed
        ConfirmaConsulta cc = new ConfirmaConsulta();
        cc.setVisible(true);
    }//GEN-LAST:event_btConfirmarConsultaActionPerformed

    private void btVisualizarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVisualizarConsultaActionPerformed
        Prontuario prontuario = new Prontuario();
        prontuario.setVisible(true);
    }//GEN-LAST:event_btVisualizarConsultaActionPerformed

    private void btAgendarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgendarConsultaActionPerformed
        AgendaConsulta ac = new AgendaConsulta();
        ac.setVisible(true);
    }//GEN-LAST:event_btAgendarConsultaActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_btSairActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_fundo;
    private javax.swing.JButton btAgendarConsulta;
    private javax.swing.JButton btCadastrarPaciente;
    private javax.swing.JButton btCancelarConsulta;
    private javax.swing.JButton btConfirmarConsulta;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btVisualizarConsulta;
    // End of variables declaration//GEN-END:variables


}
