package com.galenus.telas;

import com.galenus.dao.AgendaDAO;
import com.galenus.dao.PacienteDAO;
import com.galenus.model.Agenda;
import com.galenus.model.Paciente;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;

/**
 * @author arthu
 */
@Component
@Slf4j
public class AreaMedico extends javax.swing.JFrame {

    private final AgendaDAO agendaDAO = new AgendaDAO();
    private final PacienteDAO pacienteDAO = new PacienteDAO();

    public static Paciente paciente = new Paciente();
    public static List<Agenda> listAgenda = new ArrayList<>();
    
    private static AreaMedico INSTANCE;

    private AreaMedico() {
        initComponents();
        selectTbHorario();
        Login.getInstance().dispose();
    }

    public static AreaMedico getInstance() {
        if (INSTANCE == null) {
            INSTANCE = new AreaMedico();
        }
        return INSTANCE;
    }

    public void selectTbHorario() {
        DefaultTableModel model = (DefaultTableModel) tbHorario.getModel();
        int posLin = 0;
        model.setRowCount(posLin);

        SimpleDateFormat horaF = new SimpleDateFormat("HH:mm");

        listAgenda = agendaDAO.getAllByDate(Login.getInstance().getMedicoCrm());

        for (Agenda agenda : listAgenda) {
            paciente = pacienteDAO.getByDoc(agenda.getDocPaciente());
            model.insertRow(posLin, new Object[]{paciente.getNome(), agenda.getDocPaciente(), horaF.format(agenda.getDataHora())});
            posLin++;
        }
    }

    public Paciente clickTbConta() {
        String nome = tbHorario.getModel().getValueAt(tbHorario.getSelectedRow(), 0).toString();
        paciente = pacienteDAO.getByName(nome.trim());
        return paciente;
    }

    public Agenda getAgenda() {
        return listAgenda.get(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbHorario = new javax.swing.JTable();
        btCadConsulta = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        Label_fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbHorario.setFont(new java.awt.Font("Constantia", 0, 20)); // NOI18N
        tbHorario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "CPF", "Horário"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbHorario.setColumnSelectionAllowed(true);
        tbHorario.setGridColor(new java.awt.Color(255, 255, 255));
        tbHorario.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tbHorario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbHorarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbHorario);
        tbHorario.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 760, 370));

        btCadConsulta.setFont(new java.awt.Font("Constantia", 1, 20)); // NOI18N
        btCadConsulta.setText("Cadastrar Nova Consulta");
        btCadConsulta.setFocusPainted(false);
        btCadConsulta.setMargin(new java.awt.Insets(11, 14, 3, 14));
        btCadConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadConsultaActionPerformed(evt);
            }
        });
        getContentPane().add(btCadConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 600, 360, 50));

        btSair.setFont(new java.awt.Font("Constantia", 1, 20)); // NOI18N
        btSair.setText("Sair");
        btSair.setMargin(new java.awt.Insets(11, 14, 3, 14));
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        getContentPane().add(btSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 640, 160, 40));

        Label_fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Área do Médico.png"))); // NOI18N
        getContentPane().add(Label_fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCadConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadConsultaActionPerformed
        AgendaConsulta ac = new AgendaConsulta();
        ac.setVisible(true);
    }//GEN-LAST:event_btCadConsultaActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        dispose();
        Login.getInstance().setVisible(true);
    }//GEN-LAST:event_btSairActionPerformed

    private void tbHorarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHorarioMouseClicked
        Prontuario prontuario = new Prontuario();
        prontuario.setVisible(true);
    }//GEN-LAST:event_tbHorarioMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_fundo;
    private javax.swing.JButton btCadConsulta;
    private javax.swing.JButton btSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbHorario;
    // End of variables declaration//GEN-END:variables
}
