/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.galenus.telas;

import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.awt.Color;

/**
 *
 * @author arthu
 */
@Component
@Slf4j
public class ConfirmaConsulta extends javax.swing.JFrame {

    /**
     * Creates new form RCP_Confirmar_Con
     */
    public ConfirmaConsulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtField_Nome = new javax.swing.JTextField();
        txtFieldTelefone = new javax.swing.JTextField();
        txtField_CPF = new javax.swing.JTextField();
        cBoxPagamento = new javax.swing.JComboBox<>();
        cBoxMedico = new javax.swing.JComboBox<>();
        cBoxEspecialidade = new javax.swing.JComboBox<>();
        cBoxDia = new javax.swing.JComboBox<>();
        cBoxMes = new javax.swing.JComboBox<>();
        cBoxAno = new javax.swing.JComboBox<>();
        cBoxHorario = new javax.swing.JComboBox<>();
        txtFieldPagamento = new javax.swing.JTextField();
        txtField_Medico = new javax.swing.JTextField();
        txFieldEspecialidade = new javax.swing.JTextField();
        txtField_Data = new javax.swing.JTextField();
        txtFieldHorario = new javax.swing.JTextField();
        btConfirmar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        Label_fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtField_Nome.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtField_Nome.setForeground(new java.awt.Color(153, 153, 153));
        txtField_Nome.setText("Nome:");
        txtField_Nome.setMargin(new java.awt.Insets(2, 10, 2, 6));
        txtField_Nome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtField_NomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtField_NomeFocusLost(evt);
            }
        });
        getContentPane().add(txtField_Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 360, 50));

        txtFieldTelefone.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFieldTelefone.setForeground(new java.awt.Color(153, 153, 153));
        txtFieldTelefone.setText("Telefone:");
        txtFieldTelefone.setMargin(new java.awt.Insets(2, 10, 2, 6));
        txtFieldTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFieldTelefoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldTelefoneFocusLost(evt);
            }
        });
        txtFieldTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldTelefoneActionPerformed(evt);
            }
        });
        getContentPane().add(txtFieldTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 360, 50));

        txtField_CPF.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtField_CPF.setForeground(new java.awt.Color(153, 153, 153));
        txtField_CPF.setText("CPF:");
        txtField_CPF.setMargin(new java.awt.Insets(2, 10, 2, 6));
        txtField_CPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtField_CPFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtField_CPFFocusLost(evt);
            }
        });
        getContentPane().add(txtField_CPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 360, 50));

        cBoxPagamento.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cBoxPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dinheiro", "Cartão", "Plano de Saúde", "Retorno", " " }));
        cBoxPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxPagamentoActionPerformed(evt);
            }
        });
        getContentPane().add(cBoxPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 310, 220, 50));

        cBoxMedico.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cBoxMedico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cBoxMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxMedicoActionPerformed(evt);
            }
        });
        getContentPane().add(cBoxMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 220, 50));

        cBoxEspecialidade.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cBoxEspecialidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cBoxEspecialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxEspecialidadeActionPerformed(evt);
            }
        });
        getContentPane().add(cBoxEspecialidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 410, 220, 50));

        cBoxDia.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cBoxDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cBoxDia.setBorder(null);
        cBoxDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxDiaActionPerformed(evt);
            }
        });
        getContentPane().add(cBoxDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 510, 70, 50));

        cBoxMes.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cBoxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro ", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        cBoxMes.setBorder(null);
        cBoxMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxMesActionPerformed(evt);
            }
        });
        getContentPane().add(cBoxMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 510, 130, 50));

        cBoxAno.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cBoxAno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        cBoxAno.setBorder(null);
        cBoxAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxAnoActionPerformed(evt);
            }
        });
        getContentPane().add(cBoxAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 510, 90, 50));

        cBoxHorario.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cBoxHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "              08 : 00", "              08 : 30", "              09 : 00", "              09 : 30", "              10 : 00", "              10 : 30", "              11 : 00", "              11 : 30", "              13 : 00", "              13 : 30", "              14 : 00", "              14 : 30", "              15 : 00", "              15 : 30", "              16 : 00", "              16 : 30", "              17 : 00" }));
        cBoxHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxHorarioActionPerformed(evt);
            }
        });
        getContentPane().add(cBoxHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 510, 220, 50));

        txtFieldPagamento.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFieldPagamento.setForeground(new java.awt.Color(153, 153, 153));
        txtFieldPagamento.setText("Pagamento:");
        txtFieldPagamento.setFocusable(false);
        txtFieldPagamento.setMargin(new java.awt.Insets(2, 10, 2, 6));
        txtFieldPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldPagamentoActionPerformed(evt);
            }
        });
        getContentPane().add(txtFieldPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, 360, 50));

        txtField_Medico.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtField_Medico.setForeground(new java.awt.Color(153, 153, 153));
        txtField_Medico.setText("Médico:");
        txtField_Medico.setFocusable(false);
        txtField_Medico.setMargin(new java.awt.Insets(2, 10, 2, 6));
        txtField_Medico.setRequestFocusEnabled(false);
        txtField_Medico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_MedicoActionPerformed(evt);
            }
        });
        getContentPane().add(txtField_Medico, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 360, 50));

        txFieldEspecialidade.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txFieldEspecialidade.setForeground(new java.awt.Color(153, 153, 153));
        txFieldEspecialidade.setText("Especialidade:");
        txFieldEspecialidade.setFocusable(false);
        txFieldEspecialidade.setMargin(new java.awt.Insets(2, 10, 2, 6));
        txFieldEspecialidade.setRequestFocusEnabled(false);
        getContentPane().add(txFieldEspecialidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 410, 360, 50));

        txtField_Data.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtField_Data.setForeground(new java.awt.Color(153, 153, 153));
        txtField_Data.setText("Data:");
        txtField_Data.setFocusable(false);
        txtField_Data.setMargin(new java.awt.Insets(2, 10, 2, 6));
        txtField_Data.setRequestFocusEnabled(false);
        getContentPane().add(txtField_Data, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, 360, 50));

        txtFieldHorario.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFieldHorario.setForeground(new java.awt.Color(153, 153, 153));
        txtFieldHorario.setText("Hora:");
        txtFieldHorario.setFocusable(false);
        txtFieldHorario.setMargin(new java.awt.Insets(2, 10, 2, 6));
        txtFieldHorario.setRequestFocusEnabled(false);
        getContentPane().add(txtFieldHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 510, 360, 50));

        btConfirmar.setFont(new java.awt.Font("Constantia", 1, 20)); // NOI18N
        btConfirmar.setText("Confirmar");
        btConfirmar.setMargin(new java.awt.Insets(11, 14, 3, 14));
        getContentPane().add(btConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 640, 160, 40));

        btSair.setFont(new java.awt.Font("Constantia", 1, 20)); // NOI18N
        btSair.setText("Sair");
        btSair.setMargin(new java.awt.Insets(11, 14, 3, 14));
        getContentPane().add(btSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 640, 160, 40));

        Label_fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Confirmar Consulta.png"))); // NOI18N
        getContentPane().add(Label_fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldTelefoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldTelefoneFocusGained
        if(txtFieldTelefone.getText().equals("Telefone:")){
            txtFieldTelefone.setForeground(new Color(0, 0, 0));
            txtFieldTelefone.setText("");
        }
    }//GEN-LAST:event_txtFieldTelefoneFocusGained

    private void txtFieldTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldTelefoneFocusLost
        if(txtFieldTelefone.getText().equals("")){
            txtFieldTelefone.setText("Telefone:");
            txtFieldTelefone.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtFieldTelefoneFocusLost

    private void txtFieldTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldTelefoneActionPerformed

    private void cBoxMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cBoxMesActionPerformed

    private void cBoxEspecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxEspecialidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cBoxEspecialidadeActionPerformed

    private void cBoxDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cBoxDiaActionPerformed

    private void cBoxMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cBoxMedicoActionPerformed

    private void txtField_NomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtField_NomeFocusGained
        if(txtField_Nome.getText().equals("Nome:")){
            txtField_Nome.setForeground(new Color(0, 0, 0));
            txtField_Nome.setText("");
        }
    }//GEN-LAST:event_txtField_NomeFocusGained

    private void txtField_NomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtField_NomeFocusLost
        if(txtField_Nome.getText().equals("")){
            txtField_Nome.setText("Nome:");
            txtField_Nome.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtField_NomeFocusLost

    private void txtField_MedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_MedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_MedicoActionPerformed

    private void cBoxHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxHorarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cBoxHorarioActionPerformed

    private void cBoxAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cBoxAnoActionPerformed

    private void txtField_CPFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtField_CPFFocusGained
        if(txtField_CPF.getText().equals("CPF:")){
            txtField_CPF.setForeground(new Color(0, 0, 0));
            txtField_CPF.setText("");
        }
    }//GEN-LAST:event_txtField_CPFFocusGained

    private void txtField_CPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtField_CPFFocusLost
        if(txtField_CPF.getText().equals("")){
            txtField_CPF.setText("CPF:");
            txtField_CPF.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtField_CPFFocusLost

    private void txtFieldPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldPagamentoActionPerformed

    private void cBoxPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cBoxPagamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmaConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_fundo;
    private javax.swing.JButton btConfirmar;
    private javax.swing.JButton btSair;
    private javax.swing.JComboBox<String> cBoxAno;
    private javax.swing.JComboBox<String> cBoxDia;
    private javax.swing.JComboBox<String> cBoxEspecialidade;
    private javax.swing.JComboBox<String> cBoxHorario;
    private javax.swing.JComboBox<String> cBoxMedico;
    private javax.swing.JComboBox<String> cBoxMes;
    private javax.swing.JComboBox<String> cBoxPagamento;
    private javax.swing.JTextField txFieldEspecialidade;
    private javax.swing.JTextField txtFieldHorario;
    private javax.swing.JTextField txtFieldPagamento;
    private javax.swing.JTextField txtFieldTelefone;
    private javax.swing.JTextField txtField_CPF;
    private javax.swing.JTextField txtField_Data;
    private javax.swing.JTextField txtField_Medico;
    private javax.swing.JTextField txtField_Nome;
    // End of variables declaration//GEN-END:variables



}
