package com.galenus.telas;

import com.galenus.dao.FuncionarioDAO;
import com.galenus.dao.LogDAO;
import com.galenus.dao.MedicoDAO;
import com.galenus.model.Funcionario;
import com.galenus.model.Log;
import lombok.extern.slf4j.Slf4j;

import javax.swing.*;
import java.awt.*;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;

@Slf4j
public class Login extends javax.swing.JFrame {

    private final LogDAO logDAO = new LogDAO();
    private final FuncionarioDAO funcionarioDAO = new FuncionarioDAO();

    private static String email;

    private static Login INSTANCE;

    private Login() {
        initComponents();
    }

    public static Login getInstance() {
        if (INSTANCE == null) {
            INSTANCE = new Login();
        }
        return INSTANCE;
    }

    public String getMedicoCrm() {
        FuncionarioDAO funcionarioDAO = new FuncionarioDAO();
        MedicoDAO medicoDAO = new MedicoDAO();

        log.info(email);
        Funcionario funcionario = funcionarioDAO.getByEmail(email);

        return medicoDAO.getByDoc(funcionario.getDocumento()).getCrm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFieldEmail = new javax.swing.JTextField();
        btEntrar = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        Label_fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1240, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFieldEmail.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFieldEmail.setForeground(new java.awt.Color(31, 79, 231));
        txtFieldEmail.setText("Email:");
        txtFieldEmail.setMargin(new java.awt.Insets(2, 10, 2, 6));
        txtFieldEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFieldEmailFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldEmailFocusLost(evt);
            }
        });
        getContentPane().add(txtFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 390, 50));

        btEntrar.setFont(new java.awt.Font("Constantia", 1, 33)); // NOI18N
        btEntrar.setForeground(new java.awt.Color(31, 79, 231));
        btEntrar.setText("Entrar");
        btEntrar.setBorderPainted(false);
        btEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btEntrar.setFocusable(false);
        btEntrar.setMargin(new java.awt.Insets(15, 14, 3, 14));
        btEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(btEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, 160, 50));
        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 390, 50));

        Label_fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Inicio.png"))); // NOI18N
        getContentPane().add(Label_fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void salvaLog() {
        Log login = new Log();
        login.setDataAcesso(new Timestamp(System.currentTimeMillis()));
        try {
            login.setIpMaquina(InetAddress.getLocalHost().getHostAddress());
        } catch (UnknownHostException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        logDAO.save(login);
    }

    public boolean validaLogin(String email, String senha) {
        Funcionario funcionario = funcionarioDAO.getByEmail(email);
        if (funcionario != null) {
            return funcionario.getSenha().equals(senha);
        }
        return false;
    }

    private void txtFieldEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldEmailFocusGained
        if (txtFieldEmail.getText().equals("Email:")) {
            txtFieldEmail.setForeground(new Color(0, 0, 0));
            txtFieldEmail.setText("");
        }
    }//GEN-LAST:event_txtFieldEmailFocusGained

    private void txtFieldEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldEmailFocusLost
        if (txtFieldEmail.getText().equals("")) {
            txtFieldEmail.setText("Email:");
            txtFieldEmail.setForeground(new Color(31, 79, 231));
        }
    }//GEN-LAST:event_txtFieldEmailFocusLost

    private void btEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEntrarActionPerformed
        email = txtFieldEmail.getText();
        String senha = Arrays.toString(passwordField.getPassword()).replace("[", "").replace("]", "").replace(" ", "").replace(",", "");

        log.info(senha);
        if (validaLogin(email, senha)) {
            if (email.contains("@medico")) {
                AreaMedico.getInstance().setVisible(true);
                salvaLog();
            } else if (email.contains("@recepcao")) {
                dispose();
                AreaRecepcao.getInstance().setVisible(true);
                salvaLog();
            } else if (email.contains("@rh")) {
                dispose();
                AreaRh.getInstance().setVisible(true);
                salvaLog();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Usuário ou senha inválidos", "Erro", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_btEntrarActionPerformed

    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_fundo;
    private javax.swing.JButton btEntrar;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField txtFieldEmail;
    // End of variables declaration//GEN-END:variables
}