package com.galenus.telas;

import com.galenus.process.LoginProcess;
import lombok.extern.slf4j.Slf4j;

import javax.swing.*;
import java.awt.*;

@Slf4j
public class Login extends javax.swing.JFrame {

    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFieldEmail = new javax.swing.JTextField();
        txtFieldSenha = new javax.swing.JTextField();
        btEntrar = new javax.swing.JButton();
        Label_fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1240, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFieldEmail.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFieldEmail.setForeground(new java.awt.Color(31, 79, 231));
        txtFieldEmail.setText("Email:");
        txtFieldEmail.setMargin(new java.awt.Insets(2, 10, 2, 6));
        txtFieldEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFieldEmailFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldEmailFocusLost(evt);
            }
        });
        txtFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 390, 50));

        txtFieldSenha.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFieldSenha.setForeground(new java.awt.Color(31, 79, 231));
        txtFieldSenha.setText("Senha:");
        txtFieldSenha.setMargin(new java.awt.Insets(2, 10, 2, 6));
        txtFieldSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFieldSenhaFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldSenhaFocusLost(evt);
            }
        });
        txtFieldSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(txtFieldSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 390, 50));
        txtFieldSenha.getAccessibleContext().setAccessibleDescription("");

        btEntrar.setFont(new java.awt.Font("Constantia", 1, 33)); // NOI18N
        btEntrar.setForeground(new java.awt.Color(31, 79, 231));
        btEntrar.setText("Entrar");
        btEntrar.setBorderPainted(false);
        btEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btEntrar.setFocusable(false);
        btEntrar.setMargin(new java.awt.Insets(15, 14, 3, 14));
        btEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(btEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, 160, 50));

        Label_fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Inicio.png"))); // NOI18N
        getContentPane().add(Label_fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldSenhaActionPerformed

    private void txtFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldEmailActionPerformed

    private void txtFieldEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldEmailFocusGained
        if (txtFieldEmail.getText().equals("Email:")) {
            txtFieldEmail.setForeground(new Color(0, 0, 0));
            txtFieldEmail.setText("");
        }
    }//GEN-LAST:event_txtFieldEmailFocusGained

    private void txtFieldEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldEmailFocusLost
        if (txtFieldEmail.getText().equals("")) {
            txtFieldEmail.setText("Email:");
            txtFieldEmail.setForeground(new Color(31, 79, 231));
        }
    }//GEN-LAST:event_txtFieldEmailFocusLost

    private void txtFieldSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldSenhaFocusGained
        if (txtFieldSenha.getText().equals("Senha:")) {
            txtFieldSenha.setForeground(new Color(0, 0, 0));
            txtFieldSenha.setText("");
        }
    }//GEN-LAST:event_txtFieldSenhaFocusGained

    private void txtFieldSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldSenhaFocusLost
        if (txtFieldSenha.getText().equals("")) {
            txtFieldSenha.setText("Senha:");
            txtFieldSenha.setForeground(new Color(31, 79, 231));
        }
    }//GEN-LAST:event_txtFieldSenhaFocusLost

    private void btEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEntrarActionPerformed
        LoginProcess loginProcess = new LoginProcess();

        String email = txtFieldEmail.getText();
        String senha = txtFieldSenha.getText();

        AreaMedico areaMedico = new AreaMedico();
        AreaRecepcao areaRecepcao = new AreaRecepcao();
        AreaRh areaRh = new AreaRh();

        if (loginProcess.validaLogin(email, senha)) {
            if (email.contains("@medico")) {
                dispose();
                areaMedico.setVisible(true);
                loginProcess.salvaLog();
            } else if (email.contains("@recepcao")) {
                dispose();
                areaRecepcao.setVisible(true);
                loginProcess.salvaLog();
            } else if (email.contains("@rh")) {
                dispose();
                areaRh.setVisible(true);
                loginProcess.salvaLog();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Usuário ou senha inválidos", "Erro", JOptionPane.PLAIN_MESSAGE);
        }

    }//GEN-LAST:event_btEntrarActionPerformed

    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_fundo;
    private javax.swing.JButton btEntrar;
    private javax.swing.JTextField txtFieldEmail;
    private javax.swing.JTextField txtFieldSenha;
    // End of variables declaration//GEN-END:variables
}
