package com.galenus.telas;

import java.awt.Color;

/**
 *
 * @author arthu
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextField_Email = new javax.swing.JTextField();
        TextField_Senha = new javax.swing.JTextField();
        Button_Des_Acesso = new javax.swing.JButton();
        Label_fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1240, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextField_Email.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TextField_Email.setForeground(new java.awt.Color(31, 79, 231));
        TextField_Email.setText("Email:");
        TextField_Email.setMargin(new java.awt.Insets(2, 10, 2, 6));
        TextField_Email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextField_EmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextField_EmailFocusLost(evt);
            }
        });
        TextField_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_EmailActionPerformed(evt);
            }
        });
        getContentPane().add(TextField_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 390, 50));

        TextField_Senha.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TextField_Senha.setForeground(new java.awt.Color(31, 79, 231));
        TextField_Senha.setText("Senha:");
        TextField_Senha.setMargin(new java.awt.Insets(2, 10, 2, 6));
        TextField_Senha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextField_SenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextField_SenhaFocusLost(evt);
            }
        });
        TextField_Senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_SenhaActionPerformed(evt);
            }
        });
        getContentPane().add(TextField_Senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 390, 50));
        TextField_Senha.getAccessibleContext().setAccessibleDescription("");

        Button_Des_Acesso.setFont(new java.awt.Font("Constantia", 1, 33)); // NOI18N
        Button_Des_Acesso.setForeground(new java.awt.Color(31, 79, 231));
        Button_Des_Acesso.setText("Entrar");
        Button_Des_Acesso.setBorderPainted(false);
        Button_Des_Acesso.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Button_Des_Acesso.setFocusable(false);
        Button_Des_Acesso.setMargin(new java.awt.Insets(15, 14, 3, 14));
        Button_Des_Acesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Des_AcessoActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Des_Acesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, 160, 50));

        Label_fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Inicio.png"))); // NOI18N
        getContentPane().add(Label_fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TextField_SenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_SenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_SenhaActionPerformed

    private void TextField_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_EmailActionPerformed

    private void TextField_EmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextField_EmailFocusGained
       	if(TextField_Email.getText().equals("Email:")){
            TextField_Email.setForeground(new Color(0, 0, 0));
            TextField_Email.setText("");
        }
    }//GEN-LAST:event_TextField_EmailFocusGained

    private void TextField_EmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextField_EmailFocusLost
        if(TextField_Email.getText().equals("")){
            TextField_Email.setText("Email:");
            TextField_Email.setForeground(new Color(31, 79, 231));
        }
    }//GEN-LAST:event_TextField_EmailFocusLost

    private void TextField_SenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextField_SenhaFocusGained
        if(TextField_Senha.getText().equals("Senha:")){
            TextField_Senha.setForeground(new Color(0, 0, 0));
            TextField_Senha.setText("");
        }
    }//GEN-LAST:event_TextField_SenhaFocusGained

    private void TextField_SenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextField_SenhaFocusLost
        if(TextField_Senha.getText().equals("")){
            TextField_Senha.setText("Senha:");
            TextField_Senha.setForeground(new Color(31, 79, 231));
        }
    }//GEN-LAST:event_TextField_SenhaFocusLost

    private void Button_Des_AcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Des_AcessoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_Des_AcessoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Des_Acesso;
    private javax.swing.JLabel Label_fundo;
    private javax.swing.JTextField TextField_Email;
    private javax.swing.JTextField TextField_Senha;
    // End of variables declaration//GEN-END:variables
}
