/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.galenus.telas;

import java.awt.Color;

/**
 *
 * @author arthu
 */
public class Med_Prontuario extends javax.swing.JFrame {

    /**
     * Creates new form Med_Prontuario
     */
    public Med_Prontuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_Salvar = new javax.swing.JButton();
        Button_Limpar = new javax.swing.JButton();
        Button_Sair = new javax.swing.JButton();
        TextField_Nome = new javax.swing.JTextField();
        TextField_CPF = new javax.swing.JTextField();
        TextField_Nascimento = new javax.swing.JTextField();
        TextField_Sexo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TextField_Queicha = new javax.swing.JTextField();
        TextField_Diagnostico = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        Label_fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Button_Salvar.setFont(new java.awt.Font("Constantia", 1, 20)); // NOI18N
        Button_Salvar.setText("Salvar");
        Button_Salvar.setMargin(new java.awt.Insets(11, 14, 3, 14));
        getContentPane().add(Button_Salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 640, 160, 40));

        Button_Limpar.setFont(new java.awt.Font("Constantia", 1, 20)); // NOI18N
        Button_Limpar.setText("Limpar");
        Button_Limpar.setMargin(new java.awt.Insets(11, 14, 3, 14));
        getContentPane().add(Button_Limpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 640, 160, 40));

        Button_Sair.setFont(new java.awt.Font("Constantia", 1, 20)); // NOI18N
        Button_Sair.setText("Sair");
        Button_Sair.setMargin(new java.awt.Insets(11, 14, 3, 14));
        getContentPane().add(Button_Sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 640, 160, 40));

        TextField_Nome.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TextField_Nome.setForeground(new java.awt.Color(153, 153, 153));
        TextField_Nome.setText("Nome:");
        TextField_Nome.setMargin(new java.awt.Insets(2, 10, 2, 6));
        TextField_Nome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextField_NomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextField_NomeFocusLost(evt);
            }
        });
        getContentPane().add(TextField_Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 360, 50));

        TextField_CPF.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TextField_CPF.setForeground(new java.awt.Color(153, 153, 153));
        TextField_CPF.setText("CPF:");
        TextField_CPF.setMargin(new java.awt.Insets(2, 10, 2, 6));
        TextField_CPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextField_CPFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextField_CPFFocusLost(evt);
            }
        });
        getContentPane().add(TextField_CPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 360, 50));

        TextField_Nascimento.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TextField_Nascimento.setForeground(new java.awt.Color(153, 153, 153));
        TextField_Nascimento.setText("Data de Nascimento:");
        TextField_Nascimento.setMargin(new java.awt.Insets(2, 10, 2, 6));
        TextField_Nascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextField_NascimentoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextField_NascimentoFocusLost(evt);
            }
        });
        getContentPane().add(TextField_Nascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 360, 50));

        TextField_Sexo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TextField_Sexo.setForeground(new java.awt.Color(153, 153, 153));
        TextField_Sexo.setText("Sexo:");
        TextField_Sexo.setMargin(new java.awt.Insets(2, 10, 2, 6));
        TextField_Sexo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextField_SexoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextField_SexoFocusLost(evt);
            }
        });
        getContentPane().add(TextField_Sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 360, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Conduta");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 400, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Doênças Pre-existente");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("História Clinica");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(905, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Tratamento");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, -1, -1));

        TextField_Queicha.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TextField_Queicha.setForeground(new java.awt.Color(153, 153, 153));
        TextField_Queicha.setText("Queicha Principal:");
        TextField_Queicha.setMargin(new java.awt.Insets(2, 10, 2, 6));
        TextField_Queicha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextField_QueichaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextField_QueichaFocusLost(evt);
            }
        });
        getContentPane().add(TextField_Queicha, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 360, 50));

        TextField_Diagnostico.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TextField_Diagnostico.setForeground(new java.awt.Color(153, 153, 153));
        TextField_Diagnostico.setText("Diagnóstico:");
        TextField_Diagnostico.setMargin(new java.awt.Insets(2, 10, 2, 6));
        TextField_Diagnostico.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextField_DiagnosticoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextField_DiagnosticoFocusLost(evt);
            }
        });
        getContentPane().add(TextField_Diagnostico, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, 360, 50));

        jScrollPane1.setToolTipText("");

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jTextArea5.setToolTipText("");
        jTextArea5.setWrapStyleWord(true);
        jTextArea5.setMargin(new java.awt.Insets(40, 6, 2, 6));
        jScrollPane1.setViewportView(jTextArea5);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, -1, 190));

        jTextArea6.setColumns(20);
        jTextArea6.setRows(5);
        jTextArea6.setMargin(new java.awt.Insets(40, 6, 2, 6));
        jScrollPane2.setViewportView(jTextArea6);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 180, -1, 190));

        jTextArea7.setColumns(20);
        jTextArea7.setRows(5);
        jTextArea7.setMargin(new java.awt.Insets(40, 6, 2, 6));
        jScrollPane3.setViewportView(jTextArea7);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 390, -1, 190));

        jTextArea8.setColumns(20);
        jTextArea8.setRows(5);
        jTextArea8.setMargin(new java.awt.Insets(40, 6, 2, 6));
        jScrollPane4.setViewportView(jTextArea8);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, -1, 190));

        Label_fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Acessar Consulta.png"))); // NOI18N
        Label_fundo.setAlignmentY(0.0F);
        Label_fundo.setDoubleBuffered(true);
        Label_fundo.setFocusable(false);
        Label_fundo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Label_fundo.setRequestFocusEnabled(false);
        getContentPane().add(Label_fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextField_NomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextField_NomeFocusGained
        if(TextField_Nome.getText().equals("Nome:")){
            TextField_Nome.setForeground(new Color(0, 0, 0));
            TextField_Nome.setText("");
        }
    }//GEN-LAST:event_TextField_NomeFocusGained

    private void TextField_NomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextField_NomeFocusLost
        if(TextField_Nome.getText().equals("")){
            TextField_Nome.setText("Nome:");
            TextField_Nome.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_TextField_NomeFocusLost

    private void TextField_CPFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextField_CPFFocusGained
        if(TextField_CPF.getText().equals("CPF:")){
            TextField_CPF.setForeground(new Color(0, 0, 0));
            TextField_CPF.setText("");
        }
    }//GEN-LAST:event_TextField_CPFFocusGained

    private void TextField_CPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextField_CPFFocusLost
        if(TextField_CPF.getText().equals("")){
            TextField_CPF.setText("CPF:");
            TextField_CPF.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_TextField_CPFFocusLost

    private void TextField_NascimentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextField_NascimentoFocusGained
        if(TextField_Nascimento.getText().equals("Data de Nascimento:")){
            TextField_Nascimento.setForeground(new Color(0, 0, 0));
            TextField_Nascimento.setText("");
        }
    }//GEN-LAST:event_TextField_NascimentoFocusGained

    private void TextField_NascimentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextField_NascimentoFocusLost
        if(TextField_Nascimento.getText().equals("")){
            TextField_Nascimento.setText("Data de Nascimento:");
            TextField_Nascimento.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_TextField_NascimentoFocusLost

    private void TextField_SexoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextField_SexoFocusGained
        if(TextField_Sexo.getText().equals("Sexo:")){
            TextField_Sexo.setForeground(new Color(0, 0, 0));
            TextField_Sexo.setText("");
        }
    }//GEN-LAST:event_TextField_SexoFocusGained

    private void TextField_SexoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextField_SexoFocusLost
        if(TextField_Sexo.getText().equals("")){
            TextField_Sexo.setText("Sexo:");
            TextField_Sexo.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_TextField_SexoFocusLost

    private void TextField_QueichaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextField_QueichaFocusGained
        if(TextField_Queicha.getText().equals("Queicha Principal:")){
            TextField_Queicha.setForeground(new Color(0, 0, 0));
            TextField_Queicha.setText("");
        }
    }//GEN-LAST:event_TextField_QueichaFocusGained

    private void TextField_QueichaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextField_QueichaFocusLost
        if(TextField_Queicha.getText().equals("")){
            TextField_Queicha.setText("Queicha Principal:");
            TextField_Queicha.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_TextField_QueichaFocusLost

    private void TextField_DiagnosticoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextField_DiagnosticoFocusGained
        if(TextField_Diagnostico.getText().equals("Diagnóstico:")){
            TextField_Diagnostico.setForeground(new Color(0, 0, 0));
            TextField_Diagnostico.setText("");
        }
    }//GEN-LAST:event_TextField_DiagnosticoFocusGained

    private void TextField_DiagnosticoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextField_DiagnosticoFocusLost
        if(TextField_Diagnostico.getText().equals("")){
            TextField_Diagnostico.setText("Diagnóstico:");
            TextField_Diagnostico.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_TextField_DiagnosticoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Med_Prontuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Med_Prontuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Med_Prontuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Med_Prontuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Med_Prontuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Limpar;
    private javax.swing.JButton Button_Sair;
    private javax.swing.JButton Button_Salvar;
    private javax.swing.JLabel Label_fundo;
    private javax.swing.JTextField TextField_CPF;
    private javax.swing.JTextField TextField_Diagnostico;
    private javax.swing.JTextField TextField_Nascimento;
    private javax.swing.JTextField TextField_Nome;
    private javax.swing.JTextField TextField_Queicha;
    private javax.swing.JTextField TextField_Sexo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    // End of variables declaration//GEN-END:variables
}
