/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.galenus;

import java.awt.Color;

/**
 *
 * @author arthu
 */
public class Med_Main extends javax.swing.JFrame {

    /**
     * Creates new form Med_Main
     */
    public Med_Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Horario = new javax.swing.JTable();
        TextField_CPF_Busca = new javax.swing.JTextField();
        Button_Consulta = new javax.swing.JButton();
        Button_Cad_Consulta = new javax.swing.JButton();
        Button_Sair = new javax.swing.JButton();
        Label_fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Table_Horario.setFont(new java.awt.Font("Constantia", 0, 20)); // NOI18N
        Table_Horario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "CPF", "Horário"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_Horario.setColumnSelectionAllowed(true);
        Table_Horario.setGridColor(new java.awt.Color(255, 255, 255));
        Table_Horario.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(Table_Horario);
        Table_Horario.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 500, 340));

        TextField_CPF_Busca.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TextField_CPF_Busca.setForeground(new java.awt.Color(153, 153, 153));
        TextField_CPF_Busca.setText("CPF:");
        TextField_CPF_Busca.setMargin(new java.awt.Insets(2, 10, 2, 6));
        TextField_CPF_Busca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextField_CPF_BuscaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextField_CPF_BuscaFocusLost(evt);
            }
        });
        TextField_CPF_Busca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_CPF_BuscaActionPerformed(evt);
            }
        });
        getContentPane().add(TextField_CPF_Busca, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 290, 360, 50));

        Button_Consulta.setFont(new java.awt.Font("Constantia", 1, 20)); // NOI18N
        Button_Consulta.setText("Acessar Consulta");
        Button_Consulta.setFocusPainted(false);
        Button_Consulta.setMargin(new java.awt.Insets(11, 14, 3, 14));
        Button_Consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ConsultaActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 370, 220, 50));

        Button_Cad_Consulta.setFont(new java.awt.Font("Constantia", 1, 20)); // NOI18N
        Button_Cad_Consulta.setText("Cadastrar Consulta");
        Button_Cad_Consulta.setFocusPainted(false);
        Button_Cad_Consulta.setMargin(new java.awt.Insets(11, 14, 3, 14));
        Button_Cad_Consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Cad_ConsultaActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Cad_Consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 450, 220, 50));

        Button_Sair.setFont(new java.awt.Font("Constantia", 1, 20)); // NOI18N
        Button_Sair.setText("Sair");
        Button_Sair.setMargin(new java.awt.Insets(11, 14, 3, 14));
        getContentPane().add(Button_Sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 640, 160, 40));

        Label_fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Área do Médico.png"))); // NOI18N
        getContentPane().add(Label_fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextField_CPF_BuscaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextField_CPF_BuscaFocusGained
        if(TextField_CPF_Busca.getText().equals("CPF:")){
            TextField_CPF_Busca.setForeground(new Color(0, 0, 0));
            TextField_CPF_Busca.setText("");
        }
    }//GEN-LAST:event_TextField_CPF_BuscaFocusGained

    private void TextField_CPF_BuscaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextField_CPF_BuscaFocusLost
        if(TextField_CPF_Busca.getText().equals("")){
            TextField_CPF_Busca.setText("CPF:");
            TextField_CPF_Busca.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_TextField_CPF_BuscaFocusLost

    private void TextField_CPF_BuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_CPF_BuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_CPF_BuscaActionPerformed

    private void Button_Cad_ConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Cad_ConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_Cad_ConsultaActionPerformed

    private void Button_ConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_ConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Med_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Med_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Med_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Med_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Med_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Cad_Consulta;
    private javax.swing.JButton Button_Consulta;
    private javax.swing.JButton Button_Sair;
    private javax.swing.JLabel Label_fundo;
    private javax.swing.JTable Table_Horario;
    private javax.swing.JTextField TextField_CPF_Busca;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
