/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.galenus.telas;

import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.awt.Color;

/**
 *
 * @author arthu
 */
@Component
@Slf4j
public class Prontuario extends javax.swing.JFrame {

    /**
     * Creates new form Med_Prontuario
     */
    public Prontuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btSalvar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        txtFieldNome = new javax.swing.JTextField();
        txtFieldCpf = new javax.swing.JTextField();
        txtFieldData = new javax.swing.JTextField();
        txtFieldSexo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFieldQueixa = new javax.swing.JTextField();
        txtFieldDiagnostico = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaTratamento = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaHistClinica = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaConduta = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAreaDoencas = new javax.swing.JTextArea();
        Label_fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btSalvar.setFont(new java.awt.Font("Constantia", 1, 20)); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.setMargin(new java.awt.Insets(11, 14, 3, 14));
        getContentPane().add(btSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 640, 160, 40));

        btSair.setFont(new java.awt.Font("Constantia", 1, 20)); // NOI18N
        btSair.setText("Sair");
        btSair.setMargin(new java.awt.Insets(11, 14, 3, 14));
        getContentPane().add(btSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 640, 160, 40));

        txtFieldNome.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFieldNome.setForeground(new java.awt.Color(153, 153, 153));
        txtFieldNome.setText("Nome:");
        txtFieldNome.setMargin(new java.awt.Insets(2, 10, 2, 6));
        txtFieldNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFieldNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldNomeFocusLost(evt);
            }
        });
        getContentPane().add(txtFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 360, 50));

        txtFieldCpf.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFieldCpf.setForeground(new java.awt.Color(153, 153, 153));
        txtFieldCpf.setText("CPF:");
        txtFieldCpf.setMargin(new java.awt.Insets(2, 10, 2, 6));
        txtFieldCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFieldCpfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldCpfFocusLost(evt);
            }
        });
        getContentPane().add(txtFieldCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 360, 50));

        txtFieldData.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFieldData.setForeground(new java.awt.Color(153, 153, 153));
        txtFieldData.setText("Data de Nascimento:");
        txtFieldData.setMargin(new java.awt.Insets(2, 10, 2, 6));
        txtFieldData.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFieldDataFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldDataFocusLost(evt);
            }
        });
        getContentPane().add(txtFieldData, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 360, 50));

        txtFieldSexo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFieldSexo.setForeground(new java.awt.Color(153, 153, 153));
        txtFieldSexo.setText("Sexo:");
        txtFieldSexo.setMargin(new java.awt.Insets(2, 10, 2, 6));
        txtFieldSexo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFieldSexoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldSexoFocusLost(evt);
            }
        });
        getContentPane().add(txtFieldSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 360, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Conduta");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 400, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Doenças crônicas");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("História clinica");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(905, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Tratamento");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, -1, -1));

        txtFieldQueixa.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFieldQueixa.setForeground(new java.awt.Color(153, 153, 153));
        txtFieldQueixa.setText("Sintomas:");
        txtFieldQueixa.setMargin(new java.awt.Insets(2, 10, 2, 6));
        txtFieldQueixa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFieldQueixaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldQueixaFocusLost(evt);
            }
        });
        getContentPane().add(txtFieldQueixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 360, 50));

        txtFieldDiagnostico.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFieldDiagnostico.setForeground(new java.awt.Color(153, 153, 153));
        txtFieldDiagnostico.setText("Diagnóstico:");
        txtFieldDiagnostico.setMargin(new java.awt.Insets(2, 10, 2, 6));
        txtFieldDiagnostico.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFieldDiagnosticoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldDiagnosticoFocusLost(evt);
            }
        });
        getContentPane().add(txtFieldDiagnostico, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, 360, 50));

        jScrollPane1.setToolTipText("");

        txtAreaTratamento.setColumns(20);
        txtAreaTratamento.setRows(5);
        txtAreaTratamento.setToolTipText("");
        txtAreaTratamento.setWrapStyleWord(true);
        txtAreaTratamento.setMargin(new java.awt.Insets(40, 6, 2, 6));
        jScrollPane1.setViewportView(txtAreaTratamento);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, -1, 190));

        txtAreaHistClinica.setColumns(20);
        txtAreaHistClinica.setRows(5);
        txtAreaHistClinica.setMargin(new java.awt.Insets(40, 6, 2, 6));
        jScrollPane2.setViewportView(txtAreaHistClinica);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 180, -1, 190));

        txtAreaConduta.setColumns(20);
        txtAreaConduta.setRows(5);
        txtAreaConduta.setMargin(new java.awt.Insets(40, 6, 2, 6));
        jScrollPane3.setViewportView(txtAreaConduta);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 390, -1, 190));

        txtAreaDoencas.setColumns(20);
        txtAreaDoencas.setRows(5);
        txtAreaDoencas.setMargin(new java.awt.Insets(40, 6, 2, 6));
        jScrollPane4.setViewportView(txtAreaDoencas);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, -1, 190));

        Label_fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Acessar Consulta.png"))); // NOI18N
        Label_fundo.setAlignmentY(0.0F);
        Label_fundo.setDoubleBuffered(true);
        Label_fundo.setFocusable(false);
        Label_fundo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Label_fundo.setRequestFocusEnabled(false);
        getContentPane().add(Label_fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldNomeFocusGained
        if(txtFieldNome.getText().equals("Nome:")){
            txtFieldNome.setForeground(new Color(0, 0, 0));
            txtFieldNome.setText("");
        }
    }//GEN-LAST:event_txtFieldNomeFocusGained

    private void txtFieldNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldNomeFocusLost
        if(txtFieldNome.getText().equals("")){
            txtFieldNome.setText("Nome:");
            txtFieldNome.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtFieldNomeFocusLost

    private void txtFieldCpfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldCpfFocusGained
        if(txtFieldCpf.getText().equals("CPF:")){
            txtFieldCpf.setForeground(new Color(0, 0, 0));
            txtFieldCpf.setText("");
        }
    }//GEN-LAST:event_txtFieldCpfFocusGained

    private void txtFieldCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldCpfFocusLost
        if(txtFieldCpf.getText().equals("")){
            txtFieldCpf.setText("CPF:");
            txtFieldCpf.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtFieldCpfFocusLost

    private void txtFieldDataFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldDataFocusGained
        if(txtFieldData.getText().equals("Data de Nascimento:")){
            txtFieldData.setForeground(new Color(0, 0, 0));
            txtFieldData.setText("");
        }
    }//GEN-LAST:event_txtFieldDataFocusGained

    private void txtFieldDataFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldDataFocusLost
        if(txtFieldData.getText().equals("")){
            txtFieldData.setText("Data de Nascimento:");
            txtFieldData.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtFieldDataFocusLost

    private void txtFieldSexoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldSexoFocusGained
        if(txtFieldSexo.getText().equals("Sexo:")){
            txtFieldSexo.setForeground(new Color(0, 0, 0));
            txtFieldSexo.setText("");
        }
    }//GEN-LAST:event_txtFieldSexoFocusGained

    private void txtFieldSexoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldSexoFocusLost
        if(txtFieldSexo.getText().equals("")){
            txtFieldSexo.setText("Sexo:");
            txtFieldSexo.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtFieldSexoFocusLost

    private void txtFieldQueixaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldQueixaFocusGained
        if(txtFieldQueixa.getText().equals("Queicha Principal:")){
            txtFieldQueixa.setForeground(new Color(0, 0, 0));
            txtFieldQueixa.setText("");
        }
    }//GEN-LAST:event_txtFieldQueixaFocusGained

    private void txtFieldQueixaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldQueixaFocusLost
        if(txtFieldQueixa.getText().equals("")){
            txtFieldQueixa.setText("Queicha Principal:");
            txtFieldQueixa.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtFieldQueixaFocusLost

    private void txtFieldDiagnosticoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldDiagnosticoFocusGained
        if(txtFieldDiagnostico.getText().equals("Diagnóstico:")){
            txtFieldDiagnostico.setForeground(new Color(0, 0, 0));
            txtFieldDiagnostico.setText("");
        }
    }//GEN-LAST:event_txtFieldDiagnosticoFocusGained

    private void txtFieldDiagnosticoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldDiagnosticoFocusLost
        if(txtFieldDiagnostico.getText().equals("")){
            txtFieldDiagnostico.setText("Diagnóstico:");
            txtFieldDiagnostico.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtFieldDiagnosticoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prontuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prontuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prontuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prontuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prontuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_fundo;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btSalvar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea txtAreaConduta;
    private javax.swing.JTextArea txtAreaDoencas;
    private javax.swing.JTextArea txtAreaHistClinica;
    private javax.swing.JTextArea txtAreaTratamento;
    private javax.swing.JTextField txtFieldCpf;
    private javax.swing.JTextField txtFieldData;
    private javax.swing.JTextField txtFieldDiagnostico;
    private javax.swing.JTextField txtFieldNome;
    private javax.swing.JTextField txtFieldQueixa;
    private javax.swing.JTextField txtFieldSexo;
    // End of variables declaration//GEN-END:variables
}
