/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.galenus;

import java.awt.Color;

/**
 *
 * @author arthu
 */
public class RCP_Cad_Paciente extends javax.swing.JFrame {

    /**
     * Creates new form RCP_Cad_Paciente
     */
    public RCP_Cad_Paciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextField_Nome = new javax.swing.JTextField();
        TextField_CPF = new javax.swing.JTextField();
        TextField_Nascimento = new javax.swing.JTextField();
        TextField_Sexo = new javax.swing.JTextField();
        TextField_Telefone = new javax.swing.JTextField();
        TextField_Endereco = new javax.swing.JTextField();
        Button_Cad = new javax.swing.JButton();
        Button_Limpar = new javax.swing.JButton();
        Button_Voltar = new javax.swing.JButton();
        Label_fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextField_Nome.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TextField_Nome.setForeground(new java.awt.Color(153, 153, 153));
        TextField_Nome.setText("Nome:");
        TextField_Nome.setMargin(new java.awt.Insets(2, 10, 2, 6));
        TextField_Nome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextField_NomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextField_NomeFocusLost(evt);
            }
        });
        getContentPane().add(TextField_Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 235, 360, 50));

        TextField_CPF.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TextField_CPF.setForeground(new java.awt.Color(153, 153, 153));
        TextField_CPF.setText("CPF:");
        TextField_CPF.setMargin(new java.awt.Insets(2, 10, 2, 6));
        TextField_CPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextField_CPFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextField_CPFFocusLost(evt);
            }
        });
        getContentPane().add(TextField_CPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 335, 360, 50));

        TextField_Nascimento.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TextField_Nascimento.setForeground(new java.awt.Color(153, 153, 153));
        TextField_Nascimento.setText("Data de Nascimento:");
        TextField_Nascimento.setMargin(new java.awt.Insets(2, 10, 2, 6));
        TextField_Nascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextField_NascimentoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextField_NascimentoFocusLost(evt);
            }
        });
        getContentPane().add(TextField_Nascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 435, 360, 50));

        TextField_Sexo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TextField_Sexo.setForeground(new java.awt.Color(153, 153, 153));
        TextField_Sexo.setText("Sexo:");
        TextField_Sexo.setMargin(new java.awt.Insets(2, 10, 2, 6));
        TextField_Sexo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextField_SexoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextField_SexoFocusLost(evt);
            }
        });
        getContentPane().add(TextField_Sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 435, 360, 50));

        TextField_Telefone.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TextField_Telefone.setForeground(new java.awt.Color(153, 153, 153));
        TextField_Telefone.setText("Telefone:");
        TextField_Telefone.setMargin(new java.awt.Insets(2, 10, 2, 6));
        TextField_Telefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextField_TelefoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextField_TelefoneFocusLost(evt);
            }
        });
        getContentPane().add(TextField_Telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 335, 360, 50));

        TextField_Endereco.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TextField_Endereco.setForeground(new java.awt.Color(153, 153, 153));
        TextField_Endereco.setText("Endereço:");
        TextField_Endereco.setMargin(new java.awt.Insets(2, 10, 2, 6));
        TextField_Endereco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextField_EnderecoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextField_EnderecoFocusLost(evt);
            }
        });
        getContentPane().add(TextField_Endereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 235, 360, 50));

        Button_Cad.setFont(new java.awt.Font("Constantia", 1, 30)); // NOI18N
        Button_Cad.setText("Cadastrar");
        Button_Cad.setMargin(new java.awt.Insets(15, 14, 3, 14));
        getContentPane().add(Button_Cad, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 580, 260, 50));

        Button_Limpar.setFont(new java.awt.Font("Constantia", 1, 20)); // NOI18N
        Button_Limpar.setText("Limpar");
        Button_Limpar.setMargin(new java.awt.Insets(11, 14, 3, 14));
        getContentPane().add(Button_Limpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 640, 160, 40));

        Button_Voltar.setFont(new java.awt.Font("Constantia", 1, 20)); // NOI18N
        Button_Voltar.setText("Voltar");
        Button_Voltar.setMargin(new java.awt.Insets(11, 14, 3, 14));
        getContentPane().add(Button_Voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 640, 160, 40));

        Label_fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Cadastrar Paciente.png"))); // NOI18N
        getContentPane().add(Label_fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextField_NomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextField_NomeFocusGained
        if(TextField_Nome.getText().equals("Nome:")){
            TextField_Nome.setForeground(new Color(0, 0, 0));
            TextField_Nome.setText("");
        }
    }//GEN-LAST:event_TextField_NomeFocusGained

    private void TextField_NomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextField_NomeFocusLost
        if(TextField_Nome.getText().equals("")){
            TextField_Nome.setText("Nome:");
            TextField_Nome.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_TextField_NomeFocusLost

    private void TextField_CPFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextField_CPFFocusGained
        if(TextField_CPF.getText().equals("CPF:")){
            TextField_CPF.setForeground(new Color(0, 0, 0));
            TextField_CPF.setText("");
        }
    }//GEN-LAST:event_TextField_CPFFocusGained

    private void TextField_CPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextField_CPFFocusLost
        if(TextField_CPF.getText().equals("")){
            TextField_CPF.setText("CPF:");
            TextField_CPF.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_TextField_CPFFocusLost

    private void TextField_NascimentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextField_NascimentoFocusGained
        if(TextField_Nascimento.getText().equals("Data de Nascimento:")){
            TextField_Nascimento.setForeground(new Color(0, 0, 0));
            TextField_Nascimento.setText("");
        }
    }//GEN-LAST:event_TextField_NascimentoFocusGained

    private void TextField_NascimentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextField_NascimentoFocusLost
        if(TextField_Nascimento.getText().equals("")){
            TextField_Nascimento.setText("Data de Nascimento:");
            TextField_Nascimento.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_TextField_NascimentoFocusLost

    private void TextField_SexoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextField_SexoFocusGained
        if(TextField_Sexo.getText().equals("Sexo:")){
            TextField_Sexo.setForeground(new Color(0, 0, 0));
            TextField_Sexo.setText("");
        }
    }//GEN-LAST:event_TextField_SexoFocusGained

    private void TextField_SexoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextField_SexoFocusLost
        if(TextField_Sexo.getText().equals("")){
            TextField_Sexo.setText("Sexo:");
            TextField_Sexo.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_TextField_SexoFocusLost

    private void TextField_TelefoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextField_TelefoneFocusGained
        if(TextField_Telefone.getText().equals("Telefone:")){
            TextField_Telefone.setForeground(new Color(0, 0, 0));
            TextField_Telefone.setText("");
        }
    }//GEN-LAST:event_TextField_TelefoneFocusGained

    private void TextField_TelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextField_TelefoneFocusLost
        if(TextField_Telefone.getText().equals("")){
            TextField_Telefone.setText("Telefone:");
            TextField_Telefone.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_TextField_TelefoneFocusLost

    private void TextField_EnderecoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextField_EnderecoFocusGained
        if(TextField_Endereco.getText().equals("Endereço:")){
            TextField_Endereco.setForeground(new Color(0, 0, 0));
            TextField_Endereco.setText("");
        }
    }//GEN-LAST:event_TextField_EnderecoFocusGained

    private void TextField_EnderecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextField_EnderecoFocusLost
        if(TextField_Endereco.getText().equals("")){
            TextField_Endereco.setText("Endereço:");
            TextField_Endereco.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_TextField_EnderecoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RCP_Cad_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RCP_Cad_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RCP_Cad_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RCP_Cad_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RCP_Cad_Paciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Cad;
    private javax.swing.JButton Button_Limpar;
    private javax.swing.JButton Button_Voltar;
    private javax.swing.JLabel Label_fundo;
    private javax.swing.JTextField TextField_CPF;
    private javax.swing.JTextField TextField_Endereco;
    private javax.swing.JTextField TextField_Nascimento;
    private javax.swing.JTextField TextField_Nome;
    private javax.swing.JTextField TextField_Sexo;
    private javax.swing.JTextField TextField_Telefone;
    // End of variables declaration//GEN-END:variables

    private static RCP_Cad_Paciente telaUnica;
    
    public static RCP_Cad_Paciente getRcpCadPaciente(){
        if(telaUnica == null){
            telaUnica = new RCP_Cad_Paciente();
        }
        return telaUnica;
    }
    
}
