package com.galenus.view;

import com.galenus.controller.ConsultaDAO;
import com.galenus.model.Consulta;
import com.galenus.model.Paciente;

import javax.swing.*;
import java.awt.*;
import java.text.SimpleDateFormat;

//@Slf4j
public class Prontuario extends javax.swing.JFrame {

    private final ConsultaDAO consultaDAO = new ConsultaDAO();

    public Prontuario() {
        initComponents();
        Paciente paciente = AreaMedico.getInstance().getPacienteFromTbHorario();
        txtFieldCpf.setText(paciente.getDocumento());
        txtFieldNome.setText(paciente.getNome());
        txtFieldSexo.setText(paciente.getSexo());
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        txtFieldData.setText(dateFormat.format(paciente.getNascimento()));
        blackTxt();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelHistClinica = new javax.swing.JLabel();
        labelTratamento = new javax.swing.JLabel();
        labelConduta = new javax.swing.JLabel();
        btSalvar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        txtFieldNome = new javax.swing.JTextField();
        txtFieldCpf = new javax.swing.JTextField();
        txtFieldData = new javax.swing.JTextField();
        txtFieldSexo = new javax.swing.JTextField();
        txtFieldQueixa = new javax.swing.JTextField();
        txtFieldDiagnostico = new javax.swing.JTextField();
        scrollPaneDoencas = new javax.swing.JScrollPane();
        txtAreaDoencas = new javax.swing.JTextArea();
        scrollPaneHistClinica = new javax.swing.JScrollPane();
        txtAreaHistClinica = new javax.swing.JTextArea();
        scrollPaneTratamento = new javax.swing.JScrollPane();
        txtAreaTratamento = new javax.swing.JTextArea();
        scrollPaneConduta = new javax.swing.JScrollPane();
        txtAreaConduta = new javax.swing.JTextArea();
        labekDoencas = new javax.swing.JLabel();
        labelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelHistClinica.setBackground(new java.awt.Color(255, 255, 255));
        labelHistClinica.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        labelHistClinica.setForeground(new java.awt.Color(153, 153, 153));
        labelHistClinica.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHistClinica.setText("História clinica");
        labelHistClinica.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelHistClinica.setOpaque(true);
        getContentPane().add(labelHistClinica, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 180, 233, 30));

        labelTratamento.setBackground(new java.awt.Color(255, 255, 255));
        labelTratamento.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        labelTratamento.setForeground(new java.awt.Color(153, 153, 153));
        labelTratamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTratamento.setText("Tratamento");
        labelTratamento.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelTratamento.setOpaque(true);
        getContentPane().add(labelTratamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, 233, 30));

        labelConduta.setBackground(new java.awt.Color(255, 255, 255));
        labelConduta.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        labelConduta.setForeground(new java.awt.Color(153, 153, 153));
        labelConduta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelConduta.setText("Conduta");
        labelConduta.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelConduta.setOpaque(true);
        getContentPane().add(labelConduta, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 390, 233, 30));

        btSalvar.setFont(new java.awt.Font("Constantia", 1, 20)); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.setMargin(new java.awt.Insets(11, 14, 3, 14));
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 640, 160, 40));

        btSair.setFont(new java.awt.Font("Constantia", 1, 20)); // NOI18N
        btSair.setText("Sair");
        btSair.setMargin(new java.awt.Insets(11, 14, 3, 14));
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        getContentPane().add(btSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 640, 160, 40));

        txtFieldNome.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFieldNome.setForeground(new java.awt.Color(153, 153, 153));
        txtFieldNome.setText("Nome:");
        txtFieldNome.setFocusable(false);
        txtFieldNome.setMargin(new java.awt.Insets(2, 10, 2, 6));
        getContentPane().add(txtFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 360, 50));

        txtFieldCpf.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFieldCpf.setForeground(new java.awt.Color(153, 153, 153));
        txtFieldCpf.setText("CPF:");
        txtFieldCpf.setFocusable(false);
        txtFieldCpf.setMargin(new java.awt.Insets(2, 10, 2, 6));
        getContentPane().add(txtFieldCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 360, 50));

        txtFieldData.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFieldData.setForeground(new java.awt.Color(153, 153, 153));
        txtFieldData.setText("Data de Nascimento:");
        txtFieldData.setFocusable(false);
        txtFieldData.setMargin(new java.awt.Insets(2, 10, 2, 6));
        getContentPane().add(txtFieldData, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 360, 50));

        txtFieldSexo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFieldSexo.setForeground(new java.awt.Color(153, 153, 153));
        txtFieldSexo.setText("Sexo:");
        txtFieldSexo.setFocusable(false);
        txtFieldSexo.setMargin(new java.awt.Insets(2, 10, 2, 6));
        getContentPane().add(txtFieldSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 360, 50));

        txtFieldQueixa.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFieldQueixa.setForeground(new java.awt.Color(153, 153, 153));
        txtFieldQueixa.setText("Queixa Principal:");
        txtFieldQueixa.setMargin(new java.awt.Insets(2, 10, 2, 6));
        txtFieldQueixa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFieldQueixaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldQueixaFocusLost(evt);
            }
        });
        getContentPane().add(txtFieldQueixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 360, 50));

        txtFieldDiagnostico.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFieldDiagnostico.setForeground(new java.awt.Color(153, 153, 153));
        txtFieldDiagnostico.setText("Diagnóstico:");
        txtFieldDiagnostico.setMargin(new java.awt.Insets(2, 10, 2, 6));
        txtFieldDiagnostico.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFieldDiagnosticoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldDiagnosticoFocusLost(evt);
            }
        });
        getContentPane().add(txtFieldDiagnostico, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, 360, 50));

        txtAreaDoencas.setColumns(20);
        txtAreaDoencas.setRows(5);
        txtAreaDoencas.setMargin(new java.awt.Insets(6, 6, 2, 6));
        scrollPaneDoencas.setViewportView(txtAreaDoencas);

        getContentPane().add(scrollPaneDoencas, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 210, -1, 160));

        txtAreaHistClinica.setColumns(20);
        txtAreaHistClinica.setRows(5);
        txtAreaHistClinica.setMargin(new java.awt.Insets(6, 6, 2, 6));
        scrollPaneHistClinica.setViewportView(txtAreaHistClinica);

        getContentPane().add(scrollPaneHistClinica, new org.netbeans.lib.awtextra.AbsoluteConstraints(849, 210, -1, 160));

        scrollPaneTratamento.setToolTipText("");

        txtAreaTratamento.setColumns(20);
        txtAreaTratamento.setRows(5);
        txtAreaTratamento.setToolTipText("");
        txtAreaTratamento.setMargin(new java.awt.Insets(6, 6, 2, 6));
        scrollPaneTratamento.setViewportView(txtAreaTratamento);

        getContentPane().add(scrollPaneTratamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 420, -1, 160));

        txtAreaConduta.setColumns(20);
        txtAreaConduta.setRows(5);
        txtAreaConduta.setMargin(new java.awt.Insets(6, 6, 2, 6));
        scrollPaneConduta.setViewportView(txtAreaConduta);

        getContentPane().add(scrollPaneConduta, new org.netbeans.lib.awtextra.AbsoluteConstraints(849, 420, -1, 160));

        labekDoencas.setBackground(new java.awt.Color(255, 255, 255));
        labekDoencas.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        labekDoencas.setForeground(new java.awt.Color(153, 153, 153));
        labekDoencas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labekDoencas.setText("Doenças crônicas");
        labekDoencas.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labekDoencas.setOpaque(true);
        getContentPane().add(labekDoencas, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 233, 30));

        labelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Acessar Consulta.png"))); // NOI18N
        labelFundo.setAlignmentY(0.0F);
        labelFundo.setDoubleBuffered(true);
        labelFundo.setFocusable(false);
        labelFundo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelFundo.setRequestFocusEnabled(false);
        getContentPane().add(labelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldQueixaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldQueixaFocusGained
        if (txtFieldQueixa.getText().equals("Queicha Principal:")) {
            txtFieldQueixa.setForeground(new Color(0, 0, 0));
            txtFieldQueixa.setText("");
        }
    }//GEN-LAST:event_txtFieldQueixaFocusGained

    private void txtFieldQueixaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldQueixaFocusLost
        if (txtFieldQueixa.getText().equals("")) {
            txtFieldQueixa.setText("Queixa Principal:");
            txtFieldQueixa.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtFieldQueixaFocusLost

    private void txtFieldDiagnosticoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldDiagnosticoFocusGained
        if (txtFieldDiagnostico.getText().equals("Diagnóstico:")) {
            txtFieldDiagnostico.setForeground(new Color(0, 0, 0));
            txtFieldDiagnostico.setText("");
        }
    }//GEN-LAST:event_txtFieldDiagnosticoFocusGained

    private void txtFieldDiagnosticoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldDiagnosticoFocusLost
        if (txtFieldDiagnostico.getText().equals("")) {
            txtFieldDiagnostico.setText("Diagnóstico:");
            txtFieldDiagnostico.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtFieldDiagnosticoFocusLost

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        try {
            Consulta consulta = new Consulta();
            consulta.setPacienteDoc(txtFieldCpf.getText());
            consulta.setMedicoCrm(AreaMedico.getInstance().getCrmFromAgenda().getMedicoCrm());
            consulta.setDoencasCron(txtAreaDoencas.getText());
            consulta.setHistClinica(txtAreaHistClinica.getText());
            consulta.setTratamento(txtAreaTratamento.getText());
            consulta.setDiagostico(txtFieldDiagnostico.getText());
            consulta.setSintomas(txtFieldQueixa.getText());
            consulta.setConduta(txtAreaConduta.getText());
            consulta.setDataHora(AreaMedico.getInstance().getCrmFromAgenda().getDataHora());

            consultaDAO.save(consulta);
            JOptionPane.showMessageDialog(null, "Prontuário salvo com sucesso.", "Sucesso", JOptionPane.PLAIN_MESSAGE);
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao salvar prontuário.", "Erro", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void blackTxt(){
        txtFieldNome.setForeground(new Color(0, 0, 0));
        txtFieldCpf.setForeground(new Color(0, 0, 0));
        txtFieldData.setForeground(new Color(0, 0, 0));
        txtFieldSexo.setForeground(new Color(0, 0, 0));        
    }    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSair;
    private javax.swing.JButton btSalvar;
    private javax.swing.JLabel labekDoencas;
    private javax.swing.JLabel labelConduta;
    private javax.swing.JLabel labelFundo;
    private javax.swing.JLabel labelHistClinica;
    private javax.swing.JLabel labelTratamento;
    private javax.swing.JScrollPane scrollPaneConduta;
    private javax.swing.JScrollPane scrollPaneDoencas;
    private javax.swing.JScrollPane scrollPaneHistClinica;
    private javax.swing.JScrollPane scrollPaneTratamento;
    private javax.swing.JTextArea txtAreaConduta;
    private javax.swing.JTextArea txtAreaDoencas;
    private javax.swing.JTextArea txtAreaHistClinica;
    private javax.swing.JTextArea txtAreaTratamento;
    private javax.swing.JTextField txtFieldCpf;
    private javax.swing.JTextField txtFieldData;
    private javax.swing.JTextField txtFieldDiagnostico;
    private javax.swing.JTextField txtFieldNome;
    private javax.swing.JTextField txtFieldQueixa;
    private javax.swing.JTextField txtFieldSexo;
    // End of variables declaration//GEN-END:variables
}
